# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_client.api.workspace_security_api import WorkspaceSecurityApi


class TestWorkspaceSecurityApi(unittest.TestCase):
    """WorkspaceSecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceSecurityApi()

    def tearDown(self) -> None:
        pass

    def test_update_workspace_member_role(self) -> None:
        """Test case for update_workspace_member_role

        update workspace member role
        """
        pass

    def test_workspaces_workspace_id_members_member_id_post(self) -> None:
        """Test case for workspaces_workspace_id_members_member_id_post

        Accept or decline workspace membership invitation
        """
        pass

    def test_workspaces_workspace_id_members_post(self) -> None:
        """Test case for workspaces_workspace_id_members_post

        Create a workspace membership invite
        """
        pass


if __name__ == '__main__':
    unittest.main()
