# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.cursor import Cursor

class TestCursor(unittest.TestCase):
    """Cursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cursor:
        """Test Cursor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cursor`
        """
        model = Cursor()
        if include_optional:
            return Cursor(
                prev = 'SG93IG1hbnkgZGV2ZWxvcGVycyBkb2VzIGl0IHRha2UgdG8gc2NyZXcgaW4gYSBsaWdodGJ1bGI=',
                next = 'Tm9uZS4gSXRzIGEgaGFyZHdhcmUgcHJvYmxlbS4='
            )
        else:
            return Cursor(
        )
        """

    def testCursor(self):
        """Test Cursor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
