# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.workspace_member import WorkspaceMember

class TestWorkspaceMember(unittest.TestCase):
    """WorkspaceMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceMember:
        """Test WorkspaceMember
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceMember`
        """
        model = WorkspaceMember()
        if include_optional:
            return WorkspaceMember(
                workspace_id = '3d047892-68f1-11ee-8c99-0242ac120002',
                org_id = 'rko.12345678901234567890',
                org_name = 'Contain Co',
                org_icon = 'https://cdn.co/containco.png',
                account_id = 'rka.12345678901234567890',
                account_profile = workspace_client.models.profile_info.ProfileInfo(
                    name = 'John Doe', 
                    primary_email = 'john@containco.com', 
                    notifications_email = 'notifications@containco.com', 
                    job_title = 'CISO', 
                    design_partner_email = 'design@containco.com', 
                    work_email = 'work@containco.com', 
                    organization = 'Container Company', 
                    activity = 'Active', ),
                role = 'collaborator'
            )
        else:
            return WorkspaceMember(
        )
        """

    def testWorkspaceMember(self):
        """Test WorkspaceMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
