# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.create_workspace201_response import CreateWorkspace201Response

class TestCreateWorkspace201Response(unittest.TestCase):
    """CreateWorkspace201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkspace201Response:
        """Test CreateWorkspace201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkspace201Response`
        """
        model = CreateWorkspace201Response()
        if include_optional:
            return CreateWorkspace201Response(
                status = workspace_client.models.basic_api_reply.BasicAPIReply(
                    error = 'something bad happened', 
                    success = True, ),
                data = workspace_client.models.workspace.Workspace(
                    id = '12345678-1234-1234-1234-123456789012', 
                    name = 'My Workspace', )
            )
        else:
            return CreateWorkspace201Response(
        )
        """

    def testCreateWorkspace201Response(self):
        """Test CreateWorkspace201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
