# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.membership_accept_request import MembershipAcceptRequest

class TestMembershipAcceptRequest(unittest.TestCase):
    """MembershipAcceptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MembershipAcceptRequest:
        """Test MembershipAcceptRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MembershipAcceptRequest`
        """
        model = MembershipAcceptRequest()
        if include_optional:
            return MembershipAcceptRequest(
                selected_org_id = 'rko.12345678901234567890',
                invite_code = 'invite.123567890',
                action = 'accept'
            )
        else:
            return MembershipAcceptRequest(
        )
        """

    def testMembershipAcceptRequest(self):
        """Test MembershipAcceptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
