# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.workspace_member_status import WorkspaceMemberStatus

class TestWorkspaceMemberStatus(unittest.TestCase):
    """WorkspaceMemberStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceMemberStatus(self):
        """Test WorkspaceMemberStatus"""
        # inst = WorkspaceMemberStatus()

if __name__ == '__main__':
    unittest.main()
