# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.workspace_image import WorkspaceImage

class TestWorkspaceImage(unittest.TestCase):
    """WorkspaceImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceImage:
        """Test WorkspaceImage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceImage`
        """
        model = WorkspaceImage()
        if include_optional:
            return WorkspaceImage(
                id = '12345678-1234-1234-1234-123456789012',
                workspace_id = '12345678-1234-1234-1234-123456789012',
                registry = 'docker.io',
                repository = 'library/nginx',
                tag = 'latest',
                platform = 'linux/amd64',
                digest = 'sha256:bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b'
            )
        else:
            return WorkspaceImage(
        )
        """

    def testWorkspaceImage(self):
        """Test WorkspaceImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
