# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_client.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_add_workspace_image(self) -> None:
        """Test case for add_workspace_image

        Add a new image to the workspace
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a new workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        delete the workspace
        """
        pass

    def test_delete_workspace_member(self) -> None:
        """Test case for delete_workspace_member

        delete member from workspace
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        get the workspace
        """
        pass

    def test_get_workspace_images(self) -> None:
        """Test case for get_workspace_images

        get workspace images
        """
        pass

    def test_get_workspace_member(self) -> None:
        """Test case for get_workspace_member

        get workspace member
        """
        pass

    def test_get_workspace_members(self) -> None:
        """Test case for get_workspace_members

        get workspace members
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces the user has permissions to access
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        update the workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
