# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.get_workspace_images200_response import GetWorkspaceImages200Response

class TestGetWorkspaceImages200Response(unittest.TestCase):
    """GetWorkspaceImages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkspaceImages200Response:
        """Test GetWorkspaceImages200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWorkspaceImages200Response`
        """
        model = GetWorkspaceImages200Response()
        if include_optional:
            return GetWorkspaceImages200Response(
                status = workspace_client.models.basic_api_reply.BasicAPIReply(
                    error = 'something bad happened', 
                    success = True, ),
                count = 1,
                data = [
                    workspace_client.models.workspace_image.WorkspaceImage(
                        id = '12345678-1234-1234-1234-123456789012', 
                        workspace_id = '12345678-1234-1234-1234-123456789012', 
                        registry = 'docker.io', 
                        repository = 'library/nginx', 
                        tag = 'latest', 
                        platform = 'linux/amd64', 
                        digest = 'sha256:bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b', )
                    ]
            )
        else:
            return GetWorkspaceImages200Response(
        )
        """

    def testGetWorkspaceImages200Response(self):
        """Test GetWorkspaceImages200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
