# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.basic_api_reply import BasicAPIReply

class TestBasicAPIReply(unittest.TestCase):
    """BasicAPIReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasicAPIReply:
        """Test BasicAPIReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BasicAPIReply`
        """
        model = BasicAPIReply()
        if include_optional:
            return BasicAPIReply(
                error = 'something bad happened',
                success = True
            )
        else:
            return BasicAPIReply(
                success = True,
        )
        """

    def testBasicAPIReply(self):
        """Test BasicAPIReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
