# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.profile_info import ProfileInfo

class TestProfileInfo(unittest.TestCase):
    """ProfileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileInfo:
        """Test ProfileInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileInfo`
        """
        model = ProfileInfo()
        if include_optional:
            return ProfileInfo(
                name = 'John Doe',
                primary_email = 'john@containco.com',
                notifications_email = 'notifications@containco.com',
                job_title = 'CISO',
                design_partner_email = 'design@containco.com',
                work_email = 'work@containco.com',
                organization = 'Container Company',
                activity = 'Active'
            )
        else:
            return ProfileInfo(
        )
        """

    def testProfileInfo(self):
        """Test ProfileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
