# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.workspace_member_role import WorkspaceMemberRole

class TestWorkspaceMemberRole(unittest.TestCase):
    """WorkspaceMemberRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceMemberRole(self):
        """Test WorkspaceMemberRole"""
        # inst = WorkspaceMemberRole()

if __name__ == '__main__':
    unittest.main()
