# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.list_workspaces200_response import ListWorkspaces200Response

class TestListWorkspaces200Response(unittest.TestCase):
    """ListWorkspaces200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspaces200Response:
        """Test ListWorkspaces200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspaces200Response`
        """
        model = ListWorkspaces200Response()
        if include_optional:
            return ListWorkspaces200Response(
                status = workspace_client.models.basic_api_reply.BasicAPIReply(
                    error = 'something bad happened', 
                    success = True, ),
                count = 1,
                cursor = workspace_client.models.cursor.Cursor(
                    prev = 'SG93IG1hbnkgZGV2ZWxvcGVycyBkb2VzIGl0IHRha2UgdG8gc2NyZXcgaW4gYSBsaWdodGJ1bGI=', 
                    next = 'Tm9uZS4gSXRzIGEgaGFyZHdhcmUgcHJvYmxlbS4=', ),
                data = [
                    workspace_client.models.workspace.Workspace(
                        id = '12345678-1234-1234-1234-123456789012', 
                        name = 'My Workspace', )
                    ]
            )
        else:
            return ListWorkspaces200Response(
        )
        """

    def testListWorkspaces200Response(self):
        """Test ListWorkspaces200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
