# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace_client.models.membership_invite_request import MembershipInviteRequest

class TestMembershipInviteRequest(unittest.TestCase):
    """MembershipInviteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MembershipInviteRequest:
        """Test MembershipInviteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MembershipInviteRequest`
        """
        model = MembershipInviteRequest()
        if include_optional:
            return MembershipInviteRequest(
                emails = [
                    ''
                    ],
                expires_at = 1.337
            )
        else:
            return MembershipInviteRequest(
        )
        """

    def testMembershipInviteRequest(self):
        """Test MembershipInviteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
