# coding: utf-8

# flake8: noqa
"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from workspace_client.models.add_workspace_image201_response import AddWorkspaceImage201Response
from workspace_client.models.basic_api_reply import BasicAPIReply
from workspace_client.models.create_workspace201_response import CreateWorkspace201Response
from workspace_client.models.cursor import Cursor
from workspace_client.models.get_workspace_images200_response import GetWorkspaceImages200Response
from workspace_client.models.get_workspace_member200_response import GetWorkspaceMember200Response
from workspace_client.models.get_workspace_members200_response import GetWorkspaceMembers200Response
from workspace_client.models.list_workspaces200_response import ListWorkspaces200Response
from workspace_client.models.membership_accept_reply import MembershipAcceptReply
from workspace_client.models.membership_accept_request import MembershipAcceptRequest
from workspace_client.models.membership_invite_request import MembershipInviteRequest
from workspace_client.models.profile_info import ProfileInfo
from workspace_client.models.update_workspace_membership_role_request import UpdateWorkspaceMembershipRoleRequest
from workspace_client.models.workspace import Workspace
from workspace_client.models.workspace_image import WorkspaceImage
from workspace_client.models.workspace_member import WorkspaceMember
from workspace_client.models.workspace_member_role import WorkspaceMemberRole
from workspace_client.models.workspace_member_status import WorkspaceMemberStatus
from workspace_client.models.workspace_members import WorkspaceMembers
from workspace_client.models.workspaces_workspace_id_members_post201_response import WorkspacesWorkspaceIdMembersPost201Response
