# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from workspace_client.models.basic_api_reply import BasicAPIReply
from workspace_client.models.cursor import Cursor
from workspace_client.models.workspace_members import WorkspaceMembers
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetWorkspaceMembers200Response(BaseModel):
    """
    GetWorkspaceMembers200Response
    """ # noqa: E501
    status: Optional[BasicAPIReply] = None
    cursor: Optional[Cursor] = None
    data: Optional[WorkspaceMembers] = None
    __properties: ClassVar[List[str]] = ["status", "cursor", "data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetWorkspaceMembers200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cursor
        if self.cursor:
            _dict['cursor'] = self.cursor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetWorkspaceMembers200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": BasicAPIReply.from_dict(obj.get("status")) if obj.get("status") is not None else None,
            "cursor": Cursor.from_dict(obj.get("cursor")) if obj.get("cursor") is not None else None,
            "data": WorkspaceMembers.from_dict(obj.get("data")) if obj.get("data") is not None else None
        })
        return _obj


