# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WorkspaceMemberRole(str, Enum):
    """
    WorkspaceMemberRole
    """

    """
    allowed enum values
    """
    OWNER = 'owner'
    ADMIN = 'admin'
    EDITOR = 'editor'
    COLLABORATOR = 'collaborator'
    VIEWER = 'viewer'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkspaceMemberRole from a JSON string"""
        return cls(json.loads(json_str))


