# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from workspace_client.models.profile_info import ProfileInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkspaceMember(BaseModel):
    """
    WorkspaceMember
    """ # noqa: E501
    workspace_id: Optional[StrictStr] = None
    org_id: Optional[StrictStr] = None
    org_name: Optional[StrictStr] = None
    org_icon: Optional[StrictStr] = None
    account_id: Optional[StrictStr] = None
    account_profile: Optional[ProfileInfo] = None
    role: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["workspace_id", "org_id", "org_name", "org_icon", "account_id", "account_profile", "role"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkspaceMember from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account_profile
        if self.account_profile:
            _dict['account_profile'] = self.account_profile.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkspaceMember from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_id": obj.get("workspace_id"),
            "org_id": obj.get("org_id"),
            "org_name": obj.get("org_name"),
            "org_icon": obj.get("org_icon"),
            "account_id": obj.get("account_id"),
            "account_profile": ProfileInfo.from_dict(obj.get("account_profile")) if obj.get("account_profile") is not None else None,
            "role": obj.get("role")
        })
        return _obj


