# coding: utf-8

"""
    Slim Workspaces REST API

    This is the Workspace REST API 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WorkspaceMemberStatus(str, Enum):
    """
    WorkspaceMemberStatus
    """

    """
    allowed enum values
    """
    ACCEPTED = 'accepted'
    DECLINED = 'declined'
    PENDING = 'pending'
    EXPIRED = 'expired'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkspaceMemberStatus from a JSON string"""
        return cls(json.loads(json_str))


